

export const TODO_REQUEST = "TODO_REQUEST";
export const TODO_FAILURE = "TODO_FAILURE";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const DELETE_TODOS = "DELETE_TODOS"
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE"
