

export const TODO_REQUEST = "TODO_REQUEST";
export const TODO_FAILURE = "TODO_FAILURE";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const DELETE_TODOS = "DELETE_TODOS"
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE"
export const TOGGLE_TODOS_SUCCESS = "TOGGLE_TODOS_SUCCESS"
export const TOGGLE_TODOS_FAILURE = "TOGGLE_TODOS_FAILURE"
export const UPDATE_TODOS_REQUEST = "UPDATE_TODOS_REQUEST"
export const UPDATE_TODOS_SUCCESS = "UPDATE_TODOS_SUCCESS"
export const UPDATE_TODOS_STATUS_SUCCESS = "UPDATE_TODOS_STATUS_SUCCESS"
export const UPDATE_TODOS_FAILURE = "UPDATE_TODOS_FAILURE"

