export const AUTH_REQ = 'AUTH_REQ';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REQ_FAILURE = 'AUTH_REQ_FAILURE';